---

- include_vars: debian.yml
  when: ansible_os_family == 'Debian'

- include_vars: redhat.yml
  when: ansible_os_family == 'RedHat'

# - name: apt update
#   become: true
#   apt:
#     update_cache: true
#   when: ansible_os_family == 'Debian'

# - name: apt upgrade
#   become: true
#   apt:
#     upgrade: true
#   when: ansible_os_family == 'Debian'

- name: apt install amp
  become: true
  apt:
    pkg: '{{ item }}'
  with_items:
    - apache2
    - php
  when: ansible_os_family == 'Debian'

# - name: yum update
#   become: true
#   yum:
#     update_cache: true
#   when: ansible_os_family == 'RedHat'

# group install 'basic web server'
- name: yum install amp
  become: true
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - httpd
    - php
  when: ansible_os_family == 'RedHat'

- name: start apache
  become: true
  service:
    name: '{{ daemon }}'
    state: started
    enabled: true

- name: enable module
  become: true
  apache2_module:
    name: '{{ item }}'
    state: present
  with_items:
    - userdir
    - status
    - info
  notify:
    - reload apache
  when: ansible_os_family == 'Debian'

# - name: Commentout
#   become: true
#   lineinfile:
#     dest: /etc/apache2/mods-available/php5.conf
#     regexp: '[^#]*php_admin_flag engine Off'
#     line: '# php_admin_flag engine Off'
#     backup: true
#   when: ansible_os_family == 'Debian'

- name: enable userdir
  become: true
  lineinfile:
    dest: /etc/httpd/conf.d/userdir.conf
    backup: true
    regexp: '[^#]*UserDir disabled'
    line: '# UserDir disabled'
  notify:
    - reload apache
  when: ansible_os_family == 'RedHat'

- name: enable userdir
  become: true
  lineinfile:
    dest: /etc/httpd/conf.d/userdir.conf
    backup: true
    regexp: '#UserDir public_html'
    line: 'UserDir public_html'
  notify:
    - reload apache
  when: ansible_os_family == 'RedHat'

- name: Server Status
  become: true
  copy:
    src: server-status.conf
    dest: /etc/httpd/conf.d
  notify:
    - reload apache
  when: ansible_os_family == 'RedHat'

- name: Server Info
  become: true
  copy:
    src: server-info.conf
    dest: /etc/httpd/conf.d
  notify:
    - reload apache
  when: ansible_os_family == 'RedHat'

# - name: chmod usedir

- name: mkdir public_html
  file:
    path: ~/public_html
    state: directory

- name: template index.html
  copy:
    src: index.html
    dest: ~/public_html

- name: template info.php
  copy:
    src: info.php
    dest: ~/public_html

# firewall
# when: ansible_os_family == 'RedHat'
