---

- name: Use Japanese Repo
  become: true
  replace:
    dest: /etc/apt/sources.list
    regexp: '//archive.ubuntu.com'
    replace: '//ftp.jaist.ac.jp'
    backup: true
  when: ansible_distribution == 'Ubuntu'

- name: apt update
  become: true
  apt:
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: apt upgrade
  become: true
  apt:
    upgrade: true
  when: ansible_os_family == 'Debian'

- name: apt install
  become: true
  apt:
    pkg: '{{ item }}'
  with_items:
    - '{{ common_pkg }}'
    - '{{ debian_pkg }}'
  when: ansible_os_family == 'Debian'

# - name: Use Japanese Repo
#   become: true
#   replace:
#     dest: /etc/yum.repos.d/CentOS-Base.repo
#     regexp: ''
#     replace: ''
#     backup: true
#   when: ansible_os_family == 'Redhat'

# - name: Use Japanese Repo
#   become: true
#   replace:
#     dest: /etc/yum/pluginconf.d/fastestmirror.conf
#     regexp: ''
#     replace: ''
#     backup: true
#   when: ansible_os_family == 'Redhat'

# - name: yum update
#   become: true
#   yum:
#     update_cache: true
#   when: ansible_os_family == 'RedHat'

- name: yum group install
  become: true
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ redhat_group_pkg }}'
  when: ansible_os_family == 'RedHat'

- name: yum install
  become: true
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ common_pkg }}'
    - '{{ redhat_pkg }}'
  when: ansible_os_family == 'RedHat'

# - name: pacman
#   pacman:
#     update_cache: true

# - name: pacman
#   pacman:
#     name: '{{ item }}'
#     state: latest
#   with_items:

- name: Set zsh as default shell
  user:
    name: vagrant
    shell: /bin/zsh
  become: true

# - name: reload

