---

- include_vars: from_host.yml
  when: "'from_host' in group_names"

- include_vars: on_base.yml
  when: "'on_base' in group_names"

- name: set localtime
  become: true
  file:
    src: /usr/share/zoneinfo/Asia/Tokyo
    dest: /etc/localtime
    state: link
    force: true
  when: ansible_os_family == 'Debian' or
       (ansible_os_family == 'RedHat' and ansible_distribution_major_version == "6")

- name: define ja locale
  become: true
  shell: localedef -f UTF-8 -i ja_JP ja_JP
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"

- name: set locale
  become: true
  shell: localectl set-locale LANG=ja_JP.UTF-8
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"

- name: set localtime
  become: true
  shell: timedatectl set-timezone Asia/Tokyo
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"

# TODO: ver.6
- name: disable selinux
  become: true
  lineinfile:
    dest: /etc/sysconfig/selinux
    regexp: 'SELINUX=enforcing'
    line: 'SELINUX=disabled'
    backup: true
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"
